### ISSUE TITLE
Question about  1.1.0f async performance (ex. eventfd)

### ISSUE THREAD

**Issue by duadbsgh** [intel/QAT_Engine#40] opened 2017-11-06 00:37 UTC
We use Avalanche to measure SSL performance.
Measurement is a personal development proxy device, 
developed using async mode using openssl1.1.0f + qat engine.

As a result, CPU usage rate improved compared with SYNC MODE,
When reaching about 9400 CPS, the phenomenon that the speed is delayed greatly occurs ((50% of CPU at this time) occurs).

Changed the eventfd (0, EFD_NONBLOCK) part to eventfd (0,0) on the original qat_engine, but will this part cause a problem?

When doing eventfd (0, EFD_NONBLOCK) and eventfd (0, 0), I do not know whether there is a performance difference.

It is a very important task.
Please help me.

**Comment by stevelinsell** [comment] 2017-11-06 13:02
Hi @duadbsgh,

How are you using the asynchronous functionality of OpenSSL? To ellaborate after you get an SSL_ERROR_WANT_ASYNC status from an OpenSSL call are you using an epoll/select type mechanism before you recall the OpenSSL function or are you speculatively calling the OpenSSL function repeatedly until it can continue?
In the first case the assumption is that when you recall the OpenSSL function (and switch back into the fibre) you'll do a read on the eventfd and there will be data to read as that was why you got an event. In that case it won't really matter if the eventfd is declared EFD_NONBLOCK or not, as there should always be data waiting to be read.
The problem comes if you are speculatively recalling the OpenSSL function. In that case the eventfd may well not have any data waiting to be read. In that case it is crucial whether you set EFD_NONBLOCK. If you do not set it then you will block at that point until something has written to the eventfd. That means you are not able to process any other connections until that one is notified, effectively your connection processing becomes quite synchronous again. The real issue comes if you are using the same thread to write to the eventfd as you are to read from the eventfd (for instance if you use the external polling mode of the QAT Engine to poll the QAT Driver from the same thread that you call the OpenSSL functions from) In that case you could end up in a deadlock where you are blocked waiting to read from an eventfd but can never poll for responses from the QAT Driver that would result in writing to the eventfd.
On the other hand when you do set EFD_NONBLOCK, if you are speculatively recalling the OpenSSL functions, then you may end up in a tight loop switching in and out of the fibre trying to call read on the eventfd, and getting EAGAIN statuses back until the eventfd has finally been written to. This could end up quite CPU intensive like you describe in your post. If your code needs to make speculative calls to retry the OpenSSL functions (i.e. you can't use an epoll/select type mechanism) then the recommendation would be to keep the EFD_NONBLOCK setting on the eventfd but use some kind of backoff mechanism when you are retrying the OpenSSL calls to try and reduce the cpu usage.

Hope that information is helpful, let me know if the explanation is not clear and I'll try again as it is quite difficult to describe.

Steve.

**Comment by duadbsgh** [comment] 2017-11-07 00:39
Hi @stevelinsell  !!

Thank you for your detailed answer.
Your answer has been useful a lot.
I will ask additional questions in your answer.

When you return SSL_ERROR_WANT_ASYNC, you are using a mechanism to play the epoll role.
My development module uses the lwip module to run an event processing routine that takes a role like epoll in lwip to process tcp / ip packets.

Since my own module plays epoll role, EFD_NONBLOCK does not appear to be important.
(Example: ./openssl speed -engine qat -elapsed -async_jobs 72 rsa2048 When performing  /openssl/apps/app.c wait_for_async with SSL_ERROR_WANT_ASYNC return, regardless of EFD_NONBLOCK, speed is the same.)

Therefore, on the proxy device, EFD_NONBLOCK because is not working properly and EFD_NONBLOCK is not used.

I will explain the detailed problem.
The test is an RSA 2048 certificate,
openssl 1.0.1m-async + Previous Using qat, you can measure the highest CPS (20000 CPS) without delaying the phenomenon.
However, with openssl 1.1.0f-async + latest qat, SSL handshake with instantaneous delay at 9400CPS causes some failures (cpu is stable).
In addition, if the certificate is an RSA 1024 certificate, it will go up to 15000 cps and some will fail.
(SSL_connect seems to have no problem, It seems that it is delayed when SSL_accept exceeds some CPS.)

Is it a phenomenon that occurs when pthread or async_wait_ctx is accumulated when executing async?
Is it also a phenomenon that I do not use the polling mode of qat engine separately?

To ensure proper use of async, polling mode is essential ?

I would like to express my gratitude to many people who are working hard for qat engine today and ask questions.

Thank you !!

**Comment by duadbsgh** [comment] 2017-11-07 09:19
We will inform you of contents that are useful in relation to the above symptoms.

The above test is a multi process environment.
Each process,
eventfd open / close in  /proc/pid/ fd increases and decreases constantly.

But when you reach 9400CPS,
eventfd open increases by 400 or more per process.

Is there a limit to the number that can be registered in eventfd?

**Comment by stevelinsell** [comment] 2017-11-07 12:32
Hi @duadbsgh,

It does sound like you are hitting some kind of limit that is causing the behaviour to change. The file limits that you mention both system wide and per process would be the ones to check. Creating an eventfd can also fail if the system is low on memory but otherwise I am not aware of limits.

What happens if you configure the QAT Engine with the option --enable-qat_warnings and build and run the tests? Does it give any indication of failures happening?

One thing to note, when an error occurs within the QAT Engine (not necessarily related to the eventfd) the eventfd will not get cleaned up within the engine unless it has never been returned to the application (this is to prevent an application having stale file descriptors). The eventfd will only be closed when the ASYNC_WAIT_CTX associated with a connection gets cleaned up (within SSL_free() for example). If you are seeing the amount of eventfds suddenly increasing by a lot it would suggest that you have a lot of incoming connections that are failing and not being cleaned up straight away. So the increasing amount of eventfd's could be a symptom of a secondary problem with the shutdown/cleanup of connections but the root cause is probably that connections are failing in some way before that.

Kind Regards,

Steve.

**Comment by stevelinsell** [comment] 2017-11-09 10:46
Hi @duadbsgh,

The QAT engine has warnings for every possible failure place so it is intriguing that you see no failures reported, perhaps the error is occurring above the QAT Engine level?
One question I have is how are you triggering on async events on the file descriptor. Are you using level triggering or edge triggering? Our example nginx patch uses edge triggering. I'm not sure how relevant that is, but it would be good to know for better understanding.
Another question I would be interested in is how many simultaneous connections are you ending up with in flight when the issue appears (as opposed to how many Connections Per Second you hit). The figure for simultaneous connections is probably relevant to why the issue is occurring and knowing how many you are hitting when the issue occurs would maybe give us a clue. For instance I have no knowledge of LwIP but could it have limits on the number of simultaneous connections it can support? Have you enabled debug output in LwIP to see what is going on at that level when the issue occurs?
The reason I am thinking about simultaneous connections is because the OpenSSL 1.1.0 QAT Engine naturally has more latency due to the design of always switching out of the fibre on every async submission. This leads to you getting more connections in progress (into the accept stage) at any one time than the OpenSSL 1.0.1 QAT Engine did for the same number of CPS. If there is a hard limit somewhere in your network stack then you could be hitting the limit whereas with the OpenSSL 1.0.1 engine you were not hitting that limit. It could also be caused by a timeout higher in your stack again caused when the latency goes past a certain point that did not happen on the OpenSSL 1.0.1 stack. That would also fit into what you observed when you managed to get a higher CPS figure using an RSA1024 cert. RSA1024 will be quicker to execute than RSA2048 so there will be reduced latency and less simultaneous connections for the same CPS allowing you to reach a higher figure before the issue occurred.

Hope this gives a few clues as what to look into,

Steve.

**Comment by duadbsgh** [comment] 2017-11-10 12:46
Hi @stevelinsell 
Thank you for your kind answer. !
I think you can solve the problem quickly.  

First of all, it is confirmed that more connections are made than OpenSSL 1.0.1 QAT.

Lwip There was no problem with debugging, and there was no limit to the number of simultaneous connections.

Let's find out and check the network stack limits and clues.
I wonder if additional questions are related to MEM_SLAB SIZE in qae_mem_util.c.

Thank you !

**Comment by duadbsgh** [comment] 2017-11-13 08:38
Hi @stevelinsell 

No matter how we look at it, there seems to be no problem.
But I found something helpful.

I am currently testing using the options below.
--enable-qat_warnings \
--enable-qat_mem_warnings \
--enable-qat_small_pkt_offload \
--disable-qat_ciphers \
--enable-qat_dh \
--enable-qat_ecdh \
--disable-qat_prf \
--disable-qat_lenstra_protection \
--enable-qat_for_openssl_master

The reason I turned off the ciphers and prf options
For CPS measurement, use communication bottleneck and INTEL AESNI to get maximum CPS.

However, if you enable-cipher and enable-prf
Rather, bottlenecks occur at lower CPSs.
small_pkt and lenstra_protection are not related to CPS.

Do you have any suggestions on the above?

Thank you !!

**Comment by stevelinsell** [comment] 2018-02-12 16:27
Closing this issue as any followup will be dealt with on issue #52

**Closed by stevelinsell** 2018-02-12 16:27 UTC
