### ISSUE TITLE
Error adding fd to epoll?

### ISSUE THREAD

**Issue by lastpepole** [intel/QAT_Engine#313] opened 2024-05-20 07:14 UTC
tail -f /var/log/qat_engine_debug.log

[DEBUG][0.607131] PID [32073] Thread [1024][e_qat.c:599:qat_engine_init()] QAT Engine initialization:
[DEBUG][0.607162] PID [32073] Thread [1024][qat_hw_init.c:511:qat_hw_init()] QAT_HW initialization:
[DEBUG][0.607167] PID [32073] Thread [1024][qat_hw_init.c:512:qat_hw_init()] - External polling: OFF
[DEBUG][0.607169] PID [32073] Thread [1024][qat_hw_init.c:513:qat_hw_init()] - Heuristic polling: OFF
[DEBUG][0.607171] PID [32073] Thread [1024][qat_hw_init.c:514:qat_hw_init()] - SW Fallback: OFF
[DEBUG][0.607172] PID [32073] Thread [1024][qat_hw_init.c:515:qat_hw_init()] - Inline polling: OFF
[DEBUG][0.607174] PID [32073] Thread [1024][qat_hw_init.c:516:qat_hw_init()] - Internal poll interval: 10000ns
[DEBUG][0.607175] PID [32073] Thread [1024][qat_hw_init.c:517:qat_hw_init()] - Epoll timeout: 1000ms
[DEBUG][0.607176] PID [32073] Thread [1024][qat_hw_init.c:518:qat_hw_init()] - Event driven polling mode: ON
[DEBUG][0.607178] PID [32073] Thread [1024][qat_hw_init.c:519:qat_hw_init()] - Instance for thread: OFF
[DEBUG][0.607179] PID [32073] Thread [1024][qat_hw_init.c:520:qat_hw_init()] - Max retry count: 5
[DEBUG][0.659624] PID [32073] Thread [1024][qat_hw_init.c:559:qat_hw_init()] Found 1 Cy instances
[WARN][0.659644] PID [32073] Thread [1024][qat_hw_init.c:626:qat_hw_init()] **Error adding fd to epoll**
[DEBUG][0.659657] PID [32073] Thread [1024][qat_hw_init.c:807:qat_hw_finish_int()] ---- QAT Finishing...

[WARN][0.659663] PID [32073] Thread [1024][qat_hw_init.c:881:qat_hw_finish_int()] **Error removing fd from epoll**
[DEBUG][0.661782] PID [32073] Thread [1024][qat_hw_init.c:907:qat_hw_finish_int()] Calling pthread_key_delete()
[WARN][0.661795] PID [32073] Thread [1024][qat_fork.c:109:engine_init_child_at_fork_handler()] Failure in qat_engine_init function
[DEBUG][0.662270] PID [32073] Thread [1024][e_qat.c:645:qat_engine_finish_int()] ---- QAT Engine Finishing...

**Comment by venkatesh6911** [comment] 2024-06-06 03:51
Can you share the QAT device config ?

**Comment by venkatesh6911** [comment] 2024-07-04 14:58
This issue is the duplicate of https://github.com/intel/QAT_Engine/issues/312 and is being tracked there.
I am closing this.

**Closed by venkatesh6911** 2024-07-04 14:58 UTC
